# Requirement 

In [1]:
import pandas as pd
import numpy as np


# Reading DataSet 

In [2]:
df = pd.read_csv("transactions_train.csv")

In [3]:
df.head()

step      type    amount     nameOrig  oldbalanceOrig  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815        170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295         21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145           181.0            0.00   
3     1  CASH_OUT    181.00   C840083671           181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720         41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  
0  M1979787155             0.0             0.0        0  
1  M2044282225             0.0             0.0        0  
2   C553264065             0.0             0.0        1  
3    C38997010         21182.0             0.0        1  
4  M1230701703             0.0             0.0        0

## getting informations about dataset 

In [4]:
SHAPE = df.shape
print(SHAPE)

(6351193, 10)


In [5]:
df.describe()

step        amount  oldbalanceOrig  newbalanceOrig  \
count  6.351193e+06  6.351193e+06    6.351193e+06    6.351193e+06   
mean   2.425553e+02  1.798155e+05    8.347957e+05    8.561696e+05   
std    1.410676e+02  6.036310e+05    2.889959e+06    2.926073e+06   
min    1.000000e+00  0.000000e+00    0.000000e+00    0.000000e+00   
25%    1.550000e+02  1.338829e+04    0.000000e+00    0.000000e+00   
50%    2.380000e+02  7.486483e+04    1.415300e+04    0.000000e+00   
75%    3.340000e+02  2.087152e+05    1.073460e+05    1.443651e+05   
max    6.990000e+02  9.244552e+07    5.958504e+07    4.958504e+07   

       oldbalanceDest  newbalanceDest       isFraud  
count    6.351193e+06    6.351193e+06  6.351193e+06  
mean     1.101043e+06    1.225372e+06  1.215047e-03  
std      3.398924e+06    3.674293e+06  3.483635e-02  
min      0.000000e+00    0.000000e+00  0.000000e+00  
25%      0.000000e+00    0.000000e+00  0.000000e+00  
50%      1.330865e+05    2.149190e+05  0.000000e+00  
75%      9.438661e+05    1.112791e+06  0.000000e+00  
max      3.560159e+08    3.561793e+08  1.000000e+00

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6351193 entries, 0 to 6351192
Data columns (total 10 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrig  float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
dtypes: float64(5), int64(2), object(3)
memory usage: 484.6+ MB


In [7]:
# print(df.isFraud.unique())
# print(df.step.unique())
print(df.step.unique())

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [8]:
df.isFraud.unique()

array([0, 1], dtype=int64)

In [9]:
df.isna().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrig    0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
dtype: int64

# EDA

## DEST ORIG

In [10]:
SHAPEF = df["isFraud"].value_counts()[1]
SHAPEF

7717

In [11]:
orig = set(list(df.nameOrig.unique()))
dest = set(list(df.nameDest.unique()))



In [12]:
inter = orig & dest 
len(inter)

1758

In [13]:
internp = list(inter)


In [14]:
dfa = df[df['nameOrig'].isin(internp)]

In [15]:
dfa["isFraud"].unique()

array([0], dtype=int64)

## Type 

In [16]:
type_ = list (df.type.unique())
type_

['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN']

In [17]:
print(len(df.loc[(df.isFraud == 1) & (df.type == 'PAYMENT')]))
print(len(df.loc[(df.isFraud == 1) & (df.type == 'TRANSFER')]))
print(len(df.loc[(df.isFraud == 1) & (df.type == 'CASH_OUT')]))
print(len(df.loc[(df.isFraud == 1) & (df.type == 'DEBIT')]))
print(len(df.loc[(df.isFraud == 1) & (df.type == 'CASH_IN')]))



0
3849
3868
0
0


In [18]:
3849+3868 == SHAPEF

True

In [19]:
type_TRANSFER = df.loc[(df.isFraud == 1) & (df.type == 'TRANSFER')]
type_CASH_OUT = df.loc[(df.isFraud == 1) & (df.type == 'CASH_OUT')]

In [20]:
X = df.loc[(df.type == 'TRANSFER') | (df.type == 'CASH_OUT')]
Y = X['isFraud']
X = X.drop(['nameOrig', 'nameDest', 'isFraud'], axis = 1)

X.loc[X.type == 'TRANSFER', 'type'] = 0
X.loc[X.type == 'CASH_OUT', 'type'] = 1
X.type = X.type.astype(int)

In [21]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2765186 entries, 2 to 6351191
Data columns (total 7 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            int32  
 2   amount          float64
 3   oldbalanceOrig  float64
 4   newbalanceOrig  float64
 5   oldbalanceDest  float64
 6   newbalanceDest  float64
dtypes: float64(5), int32(1), int64(1)
memory usage: 158.2 MB


In [22]:
(pd.DataFrame(Y)).info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2765186 entries, 2 to 6351191
Data columns (total 1 columns):
 #   Column   Dtype
---  ------   -----
 0   isFraud  int64
dtypes: int64(1)
memory usage: 42.2 MB


## Balance 

In [23]:
a = X.loc[Y == 1]
a.shape

(7717, 7)

In [24]:
X.amount

2              181.00
3              181.00
15          229133.94
19          215310.30
24          311685.89
              ...    
6351186      62372.43
6351188     162326.52
6351189     162326.52
6351190    2763398.31
6351191    2763398.31
Name: amount, Length: 2765186, dtype: float64

In [25]:
len(a.loc[(a.oldbalanceDest == 0) & (a.oldbalanceDest == 0) ])/7717


0.6507710250097188

In [26]:

len(a.loc[(a.oldbalanceDest == 0) & (a.newbalanceDest == 0)])/7717

0.495918102889724

In [27]:
X.loc[(X.oldbalanceDest == 0) & (X.newbalanceDest == 0) & (X.amount != 0) , \
      ['oldbalanceDest', 'newbalanceDest']] = - 1

In [28]:
X['difforig'] = X.newbalanceOrig + X.amount - X.oldbalanceOrig
X['diffdest'] = X.oldbalanceDest + X.amount - X.newbalanceDest

In [29]:
X

step  type      amount  oldbalanceOrig  newbalanceOrig  \
2           1     0      181.00          181.00             0.0   
3           1     1      181.00          181.00             0.0   
15          1     1   229133.94        15325.00             0.0   
19          1     0   215310.30          705.00             0.0   
24          1     0   311685.89        10835.00             0.0   
...       ...   ...         ...             ...             ...   
6351186   699     1    62372.43        62372.43             0.0   
6351188   699     0   162326.52       162326.52             0.0   
6351189   699     1   162326.52       162326.52             0.0   
6351190   699     0  2763398.31      2763398.31             0.0   
6351191   699     1  2763398.31      2763398.31             0.0   

         oldbalanceDest  newbalanceDest   difforig    diffdest  
2                 -1.00           -1.00       0.00      181.00  
3              21182.00            0.00       0.00    21363.00  
15              5083.00        51513.44  213808.94   182703.50  
19             22425.00            0.00  214605.30   237735.30  
24              6267.00      2719172.89  300850.89 -2401220.00  
...                 ...             ...        ...         ...  
6351186      1195387.47      1257759.90       0.00        0.00  
6351188           -1.00           -1.00       0.00   162326.52  
6351189            0.00       162326.52       0.00        0.00  
6351190           -1.00           -1.00       0.00  2763398.31  
6351191       339515.35      3102913.66       0.00        0.00  

[2765186 rows x 9 columns]

In [54]:
X['amount'].unique()

array([1.81000000e+02, 2.29133940e+05, 2.15310300e+05, ...,
       1.25500530e+05, 2.15013300e+05, 2.76339831e+06])

In [30]:
X.dropna(axis=0 , how='any' ,inplace=True)

# Modeling 

In [74]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [32]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [51]:
joblib.dump(scaler, 'model/scaler.pkl')

['model/scaler.pkl']

In [33]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score, roc_curve, auc,\
precision_score

In [34]:
ncols = len(X.columns)
hidden_layers = (ncols,ncols,ncols)
max_iter = 1000
MLP = MLPClassifier(hidden_layer_sizes=hidden_layers,max_iter=1000,random_state=7, verbose=True)

MLP.fit(X_train,y_train)
    

Iteration 1, loss = 0.01363667
Iteration 2, loss = 0.00438272
Iteration 3, loss = 0.00376010
Iteration 4, loss = 0.00347825
Iteration 5, loss = 0.00324325
Iteration 6, loss = 0.00311791
Iteration 7, loss = 0.00304242
Iteration 8, loss = 0.00297119
Iteration 9, loss = 0.00287420
Iteration 10, loss = 0.00284725
Iteration 11, loss = 0.00283320
Iteration 12, loss = 0.00277655
Iteration 13, loss = 0.00272578
Iteration 14, loss = 0.00271229
Iteration 15, loss = 0.00274336
Iteration 16, loss = 0.00264947
Iteration 17, loss = 0.00262979
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.


MLPClassifier(hidden_layer_sizes=(9, 9, 9), max_iter=1000, random_state=7,
              verbose=True)

In [80]:
prr = np.array( [[-1.71138145 , 0.48829646 , -0.35652285 , -0.19894806 , -0.11385874  ,-0.40421826 , -0.44419909  ,-0.325865 , 0.08492648]])

In [81]:
MLP.predict(prr)

array([0], dtype=int64)

In [35]:
predictionsMLP = MLP.predict(X_test)
CM_MLP = confusion_matrix(y_test,predictionsMLP)
CR_MLP = classification_report(y_test,predictionsMLP)
fprMLP, recallMLP, thresholdsMLP = roc_curve(y_test, predictionsMLP)
AUC_MLP = auc(fprMLP, recallMLP)
    
resultsMLP = {"Confusion Matrix":CM_MLP,"Classification Report":CR_MLP,"Area Under Curve":AUC_MLP}

In [68]:
np.where(predictionsMLP==1)


(array([    89,    257,    422, ..., 551540, 551828, 552187], dtype=int64),)

In [70]:
X_test[89]

array([-0.4354174 ,  0.48829646,  8.82425875, 34.40502749, -0.11385874,
       -0.21787489,  1.50196601, -0.325865  ,  0.04898686])

In [36]:
for i in resultsMLP:
    print(i,": \n",resultsMLP[i])

Confusion Matrix : 
 [[551450     74]
 [   301   1213]]
Classification Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    551524
           1       0.94      0.80      0.87      1514

    accuracy                           1.00    553038
   macro avg       0.97      0.90      0.93    553038
weighted avg       1.00      1.00      1.00    553038

Area Under Curve : 
 0.9005273649476057


## testing API 

In [69]:
import requests

In [71]:
a = requests.get('http://127.0.0.1:5000/')

In [72]:
a.json()

{'message': 'please check documentation to use this API'}

In [73]:
b = requests.post('https://plentinapi.herokuapp.com/' ,json = {

        'step' :'ds' ,
        'type' :'CASH_OUT' ,
        'amount' :1 , 
        'oldbalanceOrig' :1 , 
        'newbalanceOrig' :1 , 
        'oldbalanceDest' :1 , 
        'newbalanceDest' :1 ,
                                    
})

In [74]:
print(b)

<Response [422]>
